# Fitting heaviy tails to modis VCF

## Setup

```{r setup, eval=T }
load(".RData")
#simul  <- F # variable to perform or not the simulations

oldcd <-getwd()


require(pander)
require(plyr)
require(dplyr)

panderOptions('table.split.table',Inf)
panderOptions('table.style', 'multiline')
options("scipen"=6, "digits"=6)

#Load package
library(poweRlaw) 

#source("R/powerlaw/discpowerexp.R")
#source("R/powerlaw/discexp.R")
#source("R/powerlaw/zeta.R")

# Load functions for continuous ht distributions
#
source("R/powerlaw/powerexp.R")
source("R/powerlaw/exp.R")
source("R/powerlaw/pareto.R")

# Functions for the analysis
#
source("R/power_fun.r")
codeDir <- "R"


options.output <- vector("list", length=0)
options.output$GOF <- 1
options.output$ploting <- 0
options.output$data_set_name <- image_names
options.output$resultsDir <- resultsDir 
options.output$sample_data <- 0 # For testing
```

# Fit heavy tailed distributions SA (south america)

```{r conheavytailfitSA, eval=F,echo=T,message=T,warning=T}
#require(doParallel)
require(plyr)
require(dplyr)


dataDir <- "Results/Southamerica"
resultsDir <- "Results/Southamerica"

##  
#  
# ~/Dropbox1T/GlobalCriticalForest/southamerica/Results

original_bin_files <- list.files(path=dataDir,pattern="*.bin")
image_names <- unlist(strsplit(original_bin_files,".bin"))


#cn <-detectCores()
#cl <- makeCluster(cn)
#registerDoParallel(cl)

set.seed(seed=0)

#all_fit<-data.frame()
#
# Add results to existing data.frame
#
fit <- data_frame()

setwd(resultsDir)
for(i_im in 1:length(image_names))
{ 
  fit <- rbind(fit,call_fit_con_heavy_tail(options.output))
}

fit$region <- "SA" # South America

all_fit <- bind_rows(all_fit,fit)

setwd(oldcd)
rm(cl,cn,fit)


# Build a dataframe for table output
#
nn <- c("Complete",">=Xmin")
#all_fit <- mutate(all_fit,model_name=nn[match(model_name,c("Power-law", "Log-normal","Exponential","Power-law w/Exp cutoff"))])
ta <- mutate(all_fit,year=substr(data_set_name,16,19),
			 Data_Set=nn[match(model_set,c("Xmin=9", "Estimated Xmin"))]) 

#ta[ta$model_set=="<Xmin",]$xmin <-ta[ta$model_set=="Estimated Xmin",]$xmin

ta <- ta %>% arrange(model_set,year,desc(AICc_weight)) %>% 
  select(year,Data_Set,xmin,model_name,par1,par2,AICc_weight,GOFp) %>% 
  mutate(xmin=ifelse(lag(xmin,1) == xmin & !is.na(lag(xmin,1)), "", xmin ),
  	   year=ifelse(lag(year,1) == year & !is.na(lag(year,1)), "", year ),
  	   Data_Set=ifelse(lag(Data_Set,1) == Data_Set & !is.na(lag(Data_Set,1)), "", Data_Set ))

options("scipen"=4, "digits"=6)

pandoc.table(ta)


save.image()

```

# Plots fits for SA

```{r conheavytailplotSA, eval=F,echo=F,message=T,warning=T}
require(dplyr)
require(ggplot2)

dataDir <- "Results/Southamerica"
resultsDir <- "Results/Southamerica"

# Read binary data
setwd(resultsDir)
set.seed(seed=0)

ccdfPlots_one_region("SA")

setwd(oldcd)

```


# Fit heavy tails for Central America CA


```{r conheavytailfitCA, eval=F,echo=T,message=T,warning=T}

dataDir <- "Results/centralamerica"
resultsDir <- "Results/centralamerica"


original_bin_files <- list.files(path=dataDir,pattern="*.bin")
image_names <- unlist(strsplit(original_bin_files,".bin"))

set.seed(seed=0)

#all_fit<-data.frame()
#
# Add results to existing data.frame
#
fit <- data_frame()
all_fit <- data_frame()

setwd(resultsDir)
for(i_im in 1:length(image_names))
{ 
  fit <- rbind(fit,call_fit_con_heavy_tail(options.output))
}


fit$region <- "CA" # Central America

all_fit <- bind_rows(all_fit,fit)

setwd(oldcd)
rm(cl,cn,fit)


# Build a dataframe for table output
#
nn <- c("Complete",">=Xmin")
ta <- mutate(all_fit,year=substr(data_set_name,16,19),
			 Data_Set=nn[match(model_set,c("Xmin=9", "Estimated Xmin"))]) 

ta <- ta %>% arrange(region,model_set,year,desc(AICc_weight)) %>% 
  select(region,year,Data_Set,xmin,model_name,par1,par2,AICc_weight,GOFp) %>% 
  mutate(xmin=ifelse(lag(xmin,1) == xmin & !is.na(lag(xmin,1)), "", xmin ),
  	   year=ifelse(lag(year,1) == year & !is.na(lag(year,1)), "", year ),
  	   Data_Set=ifelse(lag(Data_Set,1) == Data_Set & !is.na(lag(Data_Set,1)), "", Data_Set ))

options("scipen"=4, "digits"=6)

pandoc.table(ta)


save.image()


```

# Plot fits CA

```{r conheavytailplotFitCA, eval=F,echo=F,message=T,warning=T}

dataDir <- "Results/centralamerica"
resultsDir <- "Results/centralamerica"

# Read binary data
setwd(resultsDir)
set.seed(seed=0)

for( i_im in 1:length(image_names) ){
	connection_file <- file(original_bin_files[i_im], "rb")
	data_set <- readBin(connection_file, "double", n = 10^6)
	if(options.output$sample_data>0) 
		data_set<- sample(data_set,options.output$sample_data) ### TESTING
	
	nn <- strsplit(original_bin_files[i_im],".tif")[[1]][1]
	
	# Complete data set (Xmin=1)
	#
	ff <- filter(all_fit,grepl(nn,data_set_name,ignore.case = T),model_set=="Xmin=9",region=="CA")
	nn <- ff$data_set_name[1]
	na<-paste0(substr(nn,1,6),"_", substr(nn,16,19),"_",ff$model_set[1])
	cdfplot_conpl_exp(data_set,ff,na)

	# data set< Estimated Xmin (<Xmin)
	#
	ff <- filter(all_fit,grepl(nn,data_set_name,ignore.case = T),model_set=="Estimated Xmin",region=="CA")
	na<-paste0(substr(nn,1,6),"_", substr(nn,16,19),"_",ff$model_set[1])
	cdfplot_conpl_exp(data_set,ff,na)

}
setwd(oldcd)

```

# North america fits

```{r conheavytailfitNA, eval=F,echo=T,message=T,warning=T}

dataDir <- "Results/northamerica"
resultsDir <- "Results/northamerica"


original_bin_files <- list.files(path=dataDir,pattern="*.bin")
image_names <- unlist(strsplit(original_bin_files,".bin"))

set.seed(seed=0)

#all_fit<-data.frame()
#
# Add results to existing data.frame
#
fit <- data_frame()


setwd(resultsDir)
for(i_im in 1:length(image_names))
{ 
  fit <- rbind(fit,call_fit_con_heavy_tail(options.output))
}


fit$region <- "NA" # North America

all_fit <- bind_rows(all_fit,fit)

setwd(oldcd)
rm(cl,cn,fit)


# Build a dataframe for table output
#
nn <- c("Complete",">=Xmin")
ta <- mutate(all_fit,year=substr(data_set_name,16,19),
			 Data_Set=nn[match(model_set,c("Xmin=9", "Estimated Xmin"))])

ta <- ta %>% arrange(region,model_set,year,desc(AICc_weight)) %>% 
  select(region,year,Data_Set,xmin,model_name,par1,par2,AICc_weight,GOFp) %>% 
  mutate(xmin=ifelse(lag(xmin,1) == xmin & !is.na(lag(xmin,1)), "", xmin ),
  	   year=ifelse(lag(year,1) == year & !is.na(lag(year,1)), "", year ),
  	   Data_Set=ifelse(lag(Data_Set,1) == Data_Set & !is.na(lag(Data_Set,1)), "", Data_Set ))

options("scipen"=4, "digits"=6)

pandoc.table(ta)


save.image()

```



# Plot alpha and Xmin SA & CA

```{r conheavytailplotparms, eval=F,echo=F,message=T,warning=T}
setwd(oldcd)

require(dplyr)
require(ggplot2)

ff <- filter(all_fit,delta_AICc==0) %>%
	mutate(year=substr(data_set_name,16,19), se=(par1-1)/sqrt(n))

ff$lPar1 <- sapply(ff$bPar1Quant, '[', 1)
ff$hPar1 <- sapply(ff$bPar1Quant, '[', 5)

pd <-position_dodge(.1)
g <- ggplot(ff, aes(x=year,y=par1,colour=model_set,shape=model_name)) +  theme_bw() + geom_point(position=pd)+ 
	#geom_errorbar(aes(ymin=par1-se, ymax=par1+se),width=0.0,position=pd)  +
	geom_errorbar(aes(ymin=lPar1, ymax=hPar1),width=0.5,position=pd) + ylab(expression(alpha))

g + scale_colour_discrete(name="Data Set",labels=c("Xmin=9","Estimated Xmin","<Xmin")) + scale_shape_discrete(name="Best Model",labels=c("Power","Power exp."))+ facet_grid(.~region) +scale_colour_brewer(palette="Set1",name="Region")
ggsave("figure/PowerExp_allXmin_year.png",plot=g,width=8,height=4,units="in",dpi=600)

ff <- filter(ff,model_set=="Estimated Xmin")
ff1<- group_by(ff,region) %>% summarise(malpha=mean(par1))
g <- ggplot(ff, aes(x=year,y=par1,colour=region)) +  theme_bw() + geom_point(position=pd)+ geom_errorbar(aes(ymin=lPar1, ymax=hPar1),width=0.5,position=pd) + ylab(expression(alpha))
g +scale_colour_brewer(palette="Set1",name="Region") + geom_hline(aes(yintercept=malpha,colour=region),ff1)
ggsave("figure/PowerExp_Xmin_year.png",plot=g,width=6,height=4,units="in",dpi=600)



# Plot of Xmin
#

ff <- filter(all_fit,delta_AICc==0,model_set=="Estimated Xmin") %>% mutate(year=substr(data_set_name,16,19),se=(par1-1)/sqrt(n))
ff$lPar1 <- sapply(ff$bXminQuant, '[', 1)
ff$hPar1 <- sapply(ff$bXminQuant, '[', 5)

# The regions as facets 
#
g <- ggplot(ff, aes(x=year,y=xmin)) +  theme_bw() + geom_point(shape=19)+
	geom_errorbar(aes(ymin=lPar1, ymax=hPar1),width=0.5)

g + ylab(expression(X[min])) + facet_grid(.~region)
#ggsave("EstimatedXmin_year.png",plot=g,width=6,height=4,units="in",dpi=600)

# The regions with different colours
#
pd <-position_dodge(.2)
g <- ggplot(ff, aes(x=year,y=xmin,colour=region)) +  theme_bw() + geom_point(shape=19,position=pd)+
	geom_errorbar(aes(ymin=lPar1, ymax=hPar1),width=0.5,position=pd)

g + ylab(expression(X[min])) +scale_colour_brewer(palette="Set1",name="Region") 
ggsave("figure/EstimatedXmin_year.png",plot=g,width=6,height=4,units="in",dpi=600)

# Relationship between xmin & alpha 
#
g <- ggplot(ff, aes(x=par1,y=xmin,colour=region)) +  theme_bw() + geom_point(shape=19)
g + ylab(expression(X[min])) + xlab(expression(alpha))  +scale_colour_brewer(palette="Set1",name="Region") 
ggsave("figure/Xmin_Alpha.png",plot=g,width=6,height=4,units="in",dpi=600)

#
# Mean alpha and Xmin by region
#
filter(all_fit,model_name=="Power") %>% group_by(region,model_set) %>% summarise(alpha=mean(par1),xmin=mean(xmin))

```

# Extract max patch size 

```{r extractMaxPatchSA, eval=T,echo=T,message=T,warning=T}
#require(doParallel)
require(plyr)
require(dplyr)
require(ggplot2)

dataDir <- "Results/Southamerica"
resultsDir <- "Results/Southamerica"

options.output$region <- "SA" # For testing

original_bin_files <- list.files(path=dataDir,pattern="*.bin")
image_names <- unlist(strsplit(original_bin_files,".bin"))

setwd(resultsDir)

maxSize <-max_patch_size(image_names,options.output)

setwd(oldcd)

dataDir <- "Results/northamerica"
resultsDir <- "Results/northamerica"


original_bin_files <- list.files(path=dataDir,pattern="*.bin")
image_names <- unlist(strsplit(original_bin_files,".bin"))

setwd(resultsDir)

options.output$region <- "NA" # For testing

maxSize <-rbind(maxSize,max_patch_size(image_names,options.output))

setwd(oldcd)


dataDir <- "Results/centralamerica"
resultsDir <- "Results/centralamerica"

original_bin_files <- list.files(path=dataDir,pattern="*.bin")
image_names <- unlist(strsplit(original_bin_files,".bin"))

setwd(resultsDir)

options.output$region <- "CA" # For testing

maxSize <-rbind(maxSize,max_patch_size(image_names,options.output))

setwd(oldcd)

options("scipen"=0, "digits"=6)

maxSize <- mutate(maxSize, maxSKm2=maxS*233*233/1000000)

g <- ggplot(maxSize, aes(y=maxSKm2,x=year,colour=region)) +  theme_bw() + geom_point(shape=19)
g + ylab(expression(Biggest~forest~patch~Km^2))  +scale_colour_brewer(palette="Set1",name="Region")
ggsave("figure/Smax_year.png",plot=g,width=6,height=4,units="in",dpi=600)
# ylab(expression(S[max]))
save.image()
```
